ServerName lab
Listen 4441

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule mime_module modules/mod_mime.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
LoadModule ssl_module modules/mod_ssl.so
LoadModule http2_module modules/mod_http2.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

User daemon
Group daemon
ErrorLog /proc/self/fd/2
LogLevel warn
PidFile /tmp/httpd.pid

Protocols h2 http/1.1
SSLSessionCache "shmcb:/tmp/ssl_scache(512000)"

<VirtualHost *:4441>
    ServerName lab
    SSLEngine on
    SSLCertificateFile /certs/lab.crt
    SSLCertificateKeyFile /certs/lab.key
    ProxyPreserveHost On
    ProxyPass / http://172.50.0.11:9094/
    ProxyPassReverse / http://172.50.0.11:9094/
</VirtualHost>
