serverName                lab
user                      nobody
group                     nogroup
priority                  0
autoRestart               1
quicEnable                1
quicShmDir                /dev/shm
mime                      /usr/local/lsws/conf/mime.properties
docRoot                   /usr/local/lsws/Example/html/

errorlog /usr/local/lsws/logs/error.log {
  logLevel                DEBUG
  debugLevel              0
  rollingSize             10M
}
accesslog /usr/local/lsws/logs/access.log {
  logFormat               "%h %v %t %r %>s %b"
}

tuning {
  maxConnections          1000
  maxKeepAliveReq         1000
  keepAliveTimeout        60
}

virtualHost lab {
  vhRoot                  /usr/local/lsws/Example
  configFile              /usr/local/lsws/conf/vhconf.conf
  allowSymbolLink         1
  enableScript            1
  restrained              0
}

listener HTTPS {
  address                 *:4440
  secure                  1
  keyFile                 /certs/lab.key
  certFile                /certs/lab.crt
  map                     lab *
}
