docRoot                   /usr/local/lsws/Example/html/

extProcessor backend {
  type                    proxy
  address                 172.49.0.11:9098
  maxConns                100
  initTimeout             60
  retryTimeout            0
  respBuffer              0
}

context / {
  type                    proxy
  handler                 backend
  addDefaultCharset       off
}
